services:
  warehouse-db:
    image: postgres:14
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - ./sql-data-warehouse/scripts:/scripts/:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  warehouse-db-data:

