services:
  bike_sales_warehouse:
    image: postgres:14
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - bike_sales_warehouse_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  bike_sales_warehouse_data:

